### ISSUE TITLE
Dockerhub organization

### ISSUE THREAD

**Issue by zonca** [paesanilab/docker-images#1]
I created the `paesanilab` organization on DockerHub and configured 2 auto-build repositories,
so each time we make changes to the Docker images in this repo, the container are automatically built and published on DockerHub at https://hub.docker.com/r/paesanilab/

@fpaesani @agoetz can at least 1 of you create an account on hub.docker.com with the same username that you have on github? so I can give you ownership of the organization if you need to modify anything in the future.

**Comment by agoetz** [comment]
@zonca Does it have to be the same user name? My github username is already taken on Dockerhub.

**Comment by zonca** [comment]
No problem it is just more convenient but it works either way

**Comment by agoetz** [comment]
@zonca My Dockerhub username is awgoetz

The account that I created has my picture without me uploading a picture. Maybe from my github profile, for which I use the same email? I never told docker to access my github site. Scary how data is shared...

**Comment by zonca** [comment]
It is gravatar

Il mer 2 mag 2018, 22:52 Andreas Goetz <notifications@github.com> ha
scritto:

**Comment by zonca** [comment]
ok added you to the owners
